# Gov Contracts AI - Main Docker Compose Configuration
# Co-located service configuration (requires Docker Compose v2.20+)
#
# Each service's compose file lives alongside its Dockerfile for perfect co-location.
#
# Usage:
#   docker compose up -d                    # Start all services
#   docker compose --profile dev up -d      # Start with dev tools
#   docker compose up -d postgres redis     # Start specific services
#   docker compose stop airflow-worker      # Stop specific service
#
# Service structure:
#   infrastructure/docker/[service]/
#     ├── Dockerfile       # Image definition
#     ├── compose.yml      # Service orchestration
#     ├── README.md        # Documentation
#     └── ...              # Config files
#
# Available services:
#   Core Data:
#     - postgres          PostgreSQL 16 with pgvector
#     - redis             Redis 7 cache
#     - minio             S3-compatible object storage (+ init)
#
#   ML & Search:
#     - mlflow            Experiment tracking and model registry
#     - opensearch        Full-text search engine
#     - opensearch-dashboards  Visualization UI
#
#   Orchestration:
#     - airflow           Workflow orchestration (5 containers)
#
#   Development (--profile dev):
#     - dev-tools         Adminer + RedisInsight

include:
  # Core Data Infrastructure
  - infrastructure/docker/postgres/compose.yml
  - infrastructure/docker/redis/compose.yml
  - infrastructure/docker/minio/compose.yml

  # ML & Search
  - infrastructure/docker/mlflow/compose.yml
  - infrastructure/docker/opensearch/compose.yml
  - infrastructure/docker/opensearch-dashboards/compose.yml

  # Orchestration
  - infrastructure/docker/airflow/compose.yml

  # Development Tools
  - infrastructure/docker/dev-tools/compose.yml
