# Development Tools
# Optional services for development (use --profile dev)

services:
  adminer:
    image: adminer:latest
    container_name: govcontracts-adminer
    env_file:
      - ../../../.env
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: nette
    networks:
      - govcontracts-network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dev

  redisinsight:
    image: redis/redisinsight:latest
    container_name: govcontracts-redisinsight
    env_file:
      - ../../../.env
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis_data:/db
    networks:
      - govcontracts-network
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - dev
