# OpenSearch Service
# Full-text search and analytics engine

services:
  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
    image: govcontracts-opensearch:latest
    container_name: govcontracts-opensearch
    env_file:
      - ../../../.env
    environment:
      - cluster.name=govcontracts-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - "9201:9200"   # REST API
      - "9601:9600"   # Performance Analyzer
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      govcontracts-network:
        ipv4_address: 172.30.0.11

volumes:
  opensearch_data:
